<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'HMApi\\starfederation\\datastar\\' => array($vendorDir . '/starfederation/datastar-php/src'),
    'HMApi\\' => array($baseDir . '/src'),
);
