<?php

// autoload_static.php @generated by Composer

namespace HMApi\Composer\Autoload;

class ComposerStaticInit5bc05b791c01bb0c9db11ac82e616442
{
    public static $files = array (
        '765877c22806cd3aae73f7162b2a69d7' => __DIR__ . '/..' . '/adbario/php-dot-notation/src/helpers.php',
        '09cf3936aa2ba06d40dd63bf48b69aca' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/helpers.php',
        '61d30444a2129e0ab791ff53cb4b50e2' => __DIR__ . '/../..' . '/api-for-htmx.php',
    );

    public static $prefixLengthsPsr4 = array (
        'H' => 
        array (
            'HMApi\\starfederation\\datastar\\' => 30,
            'HMApi\\Jeffreyvr\\WPSettings\\' => 27,
            'HMApi\\Adbar\\' => 12,
            'HMApi\\' => 6,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'HMApi\\starfederation\\datastar\\' => 
        array (
            0 => __DIR__ . '/..' . '/starfederation/datastar-php/src',
        ),
        'HMApi\\Jeffreyvr\\WPSettings\\' => 
        array (
            0 => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src',
        ),
        'HMApi\\Adbar\\' => 
        array (
            0 => __DIR__ . '/..' . '/adbario/php-dot-notation/src',
        ),
        'HMApi\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'HMApi\\Adbar\\Dot' => __DIR__ . '/..' . '/adbario/php-dot-notation/src/Dot.php',
        'HMApi\\Admin\\Activation' => __DIR__ . '/../..' . '/src/Admin/Activation.php',
        'HMApi\\Admin\\Options' => __DIR__ . '/../..' . '/src/Admin/Options.php',
        'HMApi\\Admin\\WPSettingsOptions' => __DIR__ . '/../..' . '/src/Admin/WPSettingsOptions.php',
        'HMApi\\Assets' => __DIR__ . '/../..' . '/src/Assets.php',
        'HMApi\\Compatibility' => __DIR__ . '/../..' . '/src/Compatibility.php',
        'HMApi\\Config' => __DIR__ . '/../..' . '/src/Config.php',
        'HMApi\\Jeffreyvr\\WPSettings\\EnqueueManager' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/EnqueueManager.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Enqueuer' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Enqueuer.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Error' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Error.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Flash' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Flash.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Option' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Option.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Options\\Checkbox' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Options/Checkbox.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Options\\Choices' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Options/Choices.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Options\\CodeEditor' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Options/CodeEditor.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Options\\Color' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Options/Color.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Options\\Image' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Options/Image.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Options\\Media' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Options/Media.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Options\\OptionAbstract' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Options/OptionAbstract.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Options\\Select' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Options/Select.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Options\\SelectMultiple' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Options/SelectMultiple.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Options\\Text' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Options/Text.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Options\\Textarea' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Options/Textarea.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Options\\Video' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Options/Video.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Options\\WPEditor' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Options/WPEditor.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Section' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Section.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Tab' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Tab.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Traits\\HasOptionLevel' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Traits/HasOptionLevel.php',
        'HMApi\\Jeffreyvr\\WPSettings\\WPSettings' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/WPSettings.php',
        'HMApi\\Libraries\\Datastar' => __DIR__ . '/../..' . '/src/Libraries/Datastar.php',
        'HMApi\\Libraries\\HTMX' => __DIR__ . '/../..' . '/src/Libraries/HTMX.php',
        'HMApi\\Main' => __DIR__ . '/../..' . '/src/Main.php',
        'HMApi\\Render' => __DIR__ . '/../..' . '/src/Render.php',
        'HMApi\\Router' => __DIR__ . '/../..' . '/src/Router.php',
        'HMApi\\Theme' => __DIR__ . '/../..' . '/src/Theme.php',
        'HMApi\\starfederation\\datastar\\Consts' => __DIR__ . '/..' . '/starfederation/datastar-php/src/Consts.php',
        'HMApi\\starfederation\\datastar\\ServerSentEventData' => __DIR__ . '/..' . '/starfederation/datastar-php/src/ServerSentEventData.php',
        'HMApi\\starfederation\\datastar\\ServerSentEventGenerator' => __DIR__ . '/..' . '/starfederation/datastar-php/src/ServerSentEventGenerator.php',
        'HMApi\\starfederation\\datastar\\enums\\EventType' => __DIR__ . '/..' . '/starfederation/datastar-php/src/enums/EventType.php',
        'HMApi\\starfederation\\datastar\\enums\\FragmentMergeMode' => __DIR__ . '/..' . '/starfederation/datastar-php/src/enums/FragmentMergeMode.php',
        'HMApi\\starfederation\\datastar\\events\\EventInterface' => __DIR__ . '/..' . '/starfederation/datastar-php/src/events/EventInterface.php',
        'HMApi\\starfederation\\datastar\\events\\EventTrait' => __DIR__ . '/..' . '/starfederation/datastar-php/src/events/EventTrait.php',
        'HMApi\\starfederation\\datastar\\events\\ExecuteScript' => __DIR__ . '/..' . '/starfederation/datastar-php/src/events/ExecuteScript.php',
        'HMApi\\starfederation\\datastar\\events\\MergeFragments' => __DIR__ . '/..' . '/starfederation/datastar-php/src/events/MergeFragments.php',
        'HMApi\\starfederation\\datastar\\events\\MergeSignals' => __DIR__ . '/..' . '/starfederation/datastar-php/src/events/MergeSignals.php',
        'HMApi\\starfederation\\datastar\\events\\RemoveFragments' => __DIR__ . '/..' . '/starfederation/datastar-php/src/events/RemoveFragments.php',
        'HMApi\\starfederation\\datastar\\events\\RemoveSignals' => __DIR__ . '/..' . '/starfederation/datastar-php/src/events/RemoveSignals.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit5bc05b791c01bb0c9db11ac82e616442::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit5bc05b791c01bb0c9db11ac82e616442::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit5bc05b791c01bb0c9db11ac82e616442::$classMap;

        }, null, ClassLoader::class);
    }
}
