<?php

// autoload_static.php @generated by Composer

namespace HyperPress\Composer\Autoload;

class ComposerStaticInitd1b91324d2ccf094110b23e3d747becf
{
    public static $files = array (
        'f42daf3eafcec374a98ace42dbc2fd4a' => __DIR__ . '/../..' . '/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'H' => 
        array (
            'HyperPress\\starfederation\\datastar\\' => 35,
            'HyperPress\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'HyperPress\\starfederation\\datastar\\' => 
        array (
            0 => __DIR__ . '/..' . '/starfederation/datastar-php/src',
        ),
        'HyperPress\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'ComposerAutoloaderInitd1b91324d2ccf094110b23e3d747becf' => __DIR__ . '/..' . '/composer/autoload_real.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'HyperPress\\Admin\\Activation' => __DIR__ . '/../..' . '/src/Admin/Activation.php',
        'HyperPress\\Admin\\Options' => __DIR__ . '/../..' . '/src/Admin/Options.php',
        'HyperPress\\Admin\\OptionsMigration' => __DIR__ . '/../..' . '/src/Admin/OptionsMigration.php',
        'HyperPress\\Assets' => __DIR__ . '/../..' . '/src/Assets.php',
        'HyperPress\\Blocks\\Block' => __DIR__ . '/../..' . '/src/Blocks/Block.php',
        'HyperPress\\Blocks\\Field' => __DIR__ . '/../..' . '/src/Blocks/Field.php',
        'HyperPress\\Blocks\\FieldGroup' => __DIR__ . '/../..' . '/src/Blocks/FieldGroup.php',
        'HyperPress\\Blocks\\Registry' => __DIR__ . '/../..' . '/src/Blocks/Registry.php',
        'HyperPress\\Blocks\\Renderer' => __DIR__ . '/../..' . '/src/Blocks/Renderer.php',
        'HyperPress\\Blocks\\RestApi' => __DIR__ . '/../..' . '/src/Blocks/RestApi.php',
        'HyperPress\\Compatibility' => __DIR__ . '/../..' . '/src/Compatibility.php',
        'HyperPress\\Composer\\Autoload\\ClassLoader' => __DIR__ . '/..' . '/composer/ClassLoader.php',
        'HyperPress\\Composer\\Autoload\\ComposerStaticInitd1b91324d2ccf094110b23e3d747becf' => __DIR__ . '/..' . '/composer/autoload_static.php',
        'HyperPress\\Config' => __DIR__ . '/../..' . '/src/Config.php',
        'HyperPress\\Fields\\BlockFieldAdapter' => __DIR__ . '/../..' . '/src/Fields/BlockFieldAdapter.php',
        'HyperPress\\Fields\\ConditionalLogic' => __DIR__ . '/../..' . '/src/Fields/ConditionalLogic.php',
        'HyperPress\\Fields\\Container\\Container' => __DIR__ . '/../..' . '/src/Fields/Container/Container.php',
        'HyperPress\\Fields\\Container\\ContainerFactory' => __DIR__ . '/../..' . '/src/Fields/Container/ContainerFactory.php',
        'HyperPress\\Fields\\Container\\PostMetaContainer' => __DIR__ . '/../..' . '/src/Fields/Container/PostMetaContainer.php',
        'HyperPress\\Fields\\Container\\TermMetaContainer' => __DIR__ . '/../..' . '/src/Fields/Container/TermMetaContainer.php',
        'HyperPress\\Fields\\Container\\UserMetaContainer' => __DIR__ . '/../..' . '/src/Fields/Container/UserMetaContainer.php',
        'HyperPress\\Fields\\CustomField' => __DIR__ . '/../..' . '/src/Fields/CustomField.php',
        'HyperPress\\Fields\\Field' => __DIR__ . '/../..' . '/src/Fields/Field.php',
        'HyperPress\\Fields\\HeadingField' => __DIR__ . '/../..' . '/src/Fields/HeadingField.php',
        'HyperPress\\Fields\\HyperFields' => __DIR__ . '/../..' . '/src/Fields/HyperFields.php',
        'HyperPress\\Fields\\OptionField' => __DIR__ . '/../..' . '/src/Fields/OptionField.php',
        'HyperPress\\Fields\\OptionsPage' => __DIR__ . '/../..' . '/src/Fields/OptionsPage.php',
        'HyperPress\\Fields\\OptionsSection' => __DIR__ . '/../..' . '/src/Fields/OptionsSection.php',
        'HyperPress\\Fields\\PostField' => __DIR__ . '/../..' . '/src/Fields/PostField.php',
        'HyperPress\\Fields\\Registry' => __DIR__ . '/../..' . '/src/Fields/Registry.php',
        'HyperPress\\Fields\\RepeaterField' => __DIR__ . '/../..' . '/src/Fields/RepeaterField.php',
        'HyperPress\\Fields\\SeparatorField' => __DIR__ . '/../..' . '/src/Fields/SeparatorField.php',
        'HyperPress\\Fields\\TabsField' => __DIR__ . '/../..' . '/src/Fields/TabsField.php',
        'HyperPress\\Fields\\TemplateLoader' => __DIR__ . '/../..' . '/src/Fields/TemplateLoader.php',
        'HyperPress\\Fields\\TermField' => __DIR__ . '/../..' . '/src/Fields/TermField.php',
        'HyperPress\\Fields\\UserField' => __DIR__ . '/../..' . '/src/Fields/UserField.php',
        'HyperPress\\Libraries\\AlpineAjaxLib' => __DIR__ . '/../..' . '/src/Libraries/AlpineAjaxLib.php',
        'HyperPress\\Libraries\\DatastarLib' => __DIR__ . '/../..' . '/src/Libraries/DatastarLib.php',
        'HyperPress\\Libraries\\HTMXLib' => __DIR__ . '/../..' . '/src/Libraries/HTMXLib.php',
        'HyperPress\\Log' => __DIR__ . '/../..' . '/src/Log.php',
        'HyperPress\\Main' => __DIR__ . '/../..' . '/src/Main.php',
        'HyperPress\\Render' => __DIR__ . '/../..' . '/src/Render.php',
        'HyperPress\\Router' => __DIR__ . '/../..' . '/src/Router.php',
        'HyperPress\\Theme' => __DIR__ . '/../..' . '/src/Theme.php',
        'HyperPress\\starfederation\\datastar\\Consts' => __DIR__ . '/..' . '/starfederation/datastar-php/src/Consts.php',
        'HyperPress\\starfederation\\datastar\\ServerSentEventData' => __DIR__ . '/..' . '/starfederation/datastar-php/src/ServerSentEventData.php',
        'HyperPress\\starfederation\\datastar\\ServerSentEventGenerator' => __DIR__ . '/..' . '/starfederation/datastar-php/src/ServerSentEventGenerator.php',
        'HyperPress\\starfederation\\datastar\\enums\\ElementPatchMode' => __DIR__ . '/..' . '/starfederation/datastar-php/src/enums/ElementPatchMode.php',
        'HyperPress\\starfederation\\datastar\\enums\\EventType' => __DIR__ . '/..' . '/starfederation/datastar-php/src/enums/EventType.php',
        'HyperPress\\starfederation\\datastar\\events\\EventInterface' => __DIR__ . '/..' . '/starfederation/datastar-php/src/events/EventInterface.php',
        'HyperPress\\starfederation\\datastar\\events\\EventTrait' => __DIR__ . '/..' . '/starfederation/datastar-php/src/events/EventTrait.php',
        'HyperPress\\starfederation\\datastar\\events\\ExecuteScript' => __DIR__ . '/..' . '/starfederation/datastar-php/src/events/ExecuteScript.php',
        'HyperPress\\starfederation\\datastar\\events\\Location' => __DIR__ . '/..' . '/starfederation/datastar-php/src/events/Location.php',
        'HyperPress\\starfederation\\datastar\\events\\PatchElements' => __DIR__ . '/..' . '/starfederation/datastar-php/src/events/PatchElements.php',
        'HyperPress\\starfederation\\datastar\\events\\PatchSignals' => __DIR__ . '/..' . '/starfederation/datastar-php/src/events/PatchSignals.php',
        'HyperPress\\starfederation\\datastar\\events\\RemoveElements' => __DIR__ . '/..' . '/starfederation/datastar-php/src/events/RemoveElements.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitd1b91324d2ccf094110b23e3d747becf::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitd1b91324d2ccf094110b23e3d747becf::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitd1b91324d2ccf094110b23e3d747becf::$classMap;

        }, null, ClassLoader::class);
    }
}
